/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as SevimlilarRouteImport } from './routes/sevimlilar'
import { Route as YetkazibBerishRouteImport } from './routes/yetkazib-berish'
import { Route as BizHaqimizdaRouteImport } from './routes/biz-haqimizda'
import { Route as AloqaRouteImport } from './routes/aloqa'
import { Route as ChegirmalarRouteImport } from './routes/chegirmalar'
import { Route as KategoriyalarRouteImport } from './routes/kategoriyalar'
import { Route as MahsulotlarRouteImport } from './routes/mahsulotlar'
import { Route as SavatchaRouteImport } from './routes/savatcha'
import { Route as MahsulotSlugRouteImport } from './routes/mahsulot.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const SevimlilarRoute = SevimlilarRouteImport.update({
  id: '/sevimlilar',
  path: '/sevimlilar',
  getParentRoute: () => rootRouteImport,
} as any)
const YetkazibBerishRoute = YetkazibBerishRouteImport.update({
  id: '/yetkazib-berish',
  path: '/yetkazib-berish',
  getParentRoute: () => rootRouteImport,
} as any)
const BizHaqimizdaRoute = BizHaqimizdaRouteImport.update({
  id: '/biz-haqimizda',
  path: '/biz-haqimizda',
  getParentRoute: () => rootRouteImport,
} as any)
const AloqaRoute = AloqaRouteImport.update({
  id: '/aloqa',
  path: '/aloqa',
  getParentRoute: () => rootRouteImport,
} as any)
const ChegirmalarRoute = ChegirmalarRouteImport.update({
  id: '/chegirmalar',
  path: '/chegirmalar',
  getParentRoute: () => rootRouteImport,
} as any)
const KategoriyalarRoute = KategoriyalarRouteImport.update({
  id: '/kategoriyalar',
  path: '/kategoriyalar',
  getParentRoute: () => rootRouteImport,
} as any)
const MahsulotlarRoute = MahsulotlarRouteImport.update({
  id: '/mahsulotlar',
  path: '/mahsulotlar',
  getParentRoute: () => rootRouteImport,
} as any)
const SavatchaRoute = SavatchaRouteImport.update({
  id: '/savatcha',
  path: '/savatcha',
  getParentRoute: () => rootRouteImport,
} as any)
const MahsulotSlugRoute = MahsulotSlugRouteImport.update({
  id: '/mahsulot/$slug',
  path: '/mahsulot/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aloqa': typeof AloqaRoute
  '/biz-haqimizda': typeof BizHaqimizdaRoute
  '/checkout': typeof CheckoutRoute
  '/chegirmalar': typeof ChegirmalarRoute
  '/faq': typeof FaqRoute
  '/kategoriyalar': typeof KategoriyalarRoute
  '/mahsulotlar': typeof MahsulotlarRoute
  '/profil': typeof ProfilRoute
  '/savatcha': typeof SavatchaRoute
  '/sevimlilar': typeof SevimlilarRoute
  '/yetkazib-berish': typeof YetkazibBerishRoute
  '/mahsulot/$slug': typeof MahsulotSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aloqa': typeof AloqaRoute
  '/biz-haqimizda': typeof BizHaqimizdaRoute
  '/checkout': typeof CheckoutRoute
  '/chegirmalar': typeof ChegirmalarRoute
  '/faq': typeof FaqRoute
  '/kategoriyalar': typeof KategoriyalarRoute
  '/mahsulotlar': typeof MahsulotlarRoute
  '/profil': typeof ProfilRoute
  '/savatcha': typeof SavatchaRoute
  '/sevimlilar': typeof SevimlilarRoute
  '/yetkazib-berish': typeof YetkazibBerishRoute
  '/mahsulot/$slug': typeof MahsulotSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aloqa': typeof AloqaRoute
  '/biz-haqimizda': typeof BizHaqimizdaRoute
  '/checkout': typeof CheckoutRoute
  '/chegirmalar': typeof ChegirmalarRoute
  '/faq': typeof FaqRoute
  '/kategoriyalar': typeof KategoriyalarRoute
  '/mahsulotlar': typeof MahsulotlarRoute
  '/profil': typeof ProfilRoute
  '/savatcha': typeof SavatchaRoute
  '/sevimlilar': typeof SevimlilarRoute
  '/yetkazib-berish': typeof YetkazibBerishRoute
  '/mahsulot/$slug': typeof MahsulotSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aloqa'
    | '/biz-haqimizda'
    | '/checkout'
    | '/chegirmalar'
    | '/faq'
    | '/kategoriyalar'
    | '/mahsulotlar'
    | '/profil'
    | '/savatcha'
    | '/sevimlilar'
    | '/yetkazib-berish'
    | '/mahsulot/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aloqa'
    | '/biz-haqimizda'
    | '/checkout'
    | '/chegirmalar'
    | '/faq'
    | '/kategoriyalar'
    | '/mahsulotlar'
    | '/profil'
    | '/savatcha'
    | '/sevimlilar'
    | '/yetkazib-berish'
    | '/mahsulot/$slug'
  id:
    | '__root__'
    | '/'
    | '/aloqa'
    | '/biz-haqimizda'
    | '/checkout'
    | '/chegirmalar'
    | '/faq'
    | '/kategoriyalar'
    | '/mahsulotlar'
    | '/profil'
    | '/savatcha'
    | '/sevimlilar'
    | '/yetkazib-berish'
    | '/mahsulot/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AloqaRoute: typeof AloqaRoute
  BizHaqimizdaRoute: typeof BizHaqimizdaRoute
  CheckoutRoute: typeof CheckoutRoute
  ChegirmalarRoute: typeof ChegirmalarRoute
  FaqRoute: typeof FaqRoute
  KategoriyalarRoute: typeof KategoriyalarRoute
  MahsulotlarRoute: typeof MahsulotlarRoute
  ProfilRoute: typeof ProfilRoute
  SavatchaRoute: typeof SavatchaRoute
  SevimlilarRoute: typeof SevimlilarRoute
  YetkazibBerishRoute: typeof YetkazibBerishRoute
  MahsulotSlugRoute: typeof MahsulotSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aloqa': {
      id: '/aloqa'
      path: '/aloqa'
      fullPath: '/aloqa'
      preLoaderRoute: typeof AloqaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biz-haqimizda': {
      id: '/biz-haqimizda'
      path: '/biz-haqimizda'
      fullPath: '/biz-haqimizda'
      preLoaderRoute: typeof BizHaqimizdaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chegirmalar': {
      id: '/chegirmalar'
      path: '/chegirmalar'
      fullPath: '/chegirmalar'
      preLoaderRoute: typeof ChegirmalarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kategoriyalar': {
      id: '/kategoriyalar'
      path: '/kategoriyalar'
      fullPath: '/kategoriyalar'
      preLoaderRoute: typeof KategoriyalarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mahsulotlar': {
      id: '/mahsulotlar'
      path: '/mahsulotlar'
      fullPath: '/mahsulotlar'
      preLoaderRoute: typeof MahsulotlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/savatcha': {
      id: '/savatcha'
      path: '/savatcha'
      fullPath: '/savatcha'
      preLoaderRoute: typeof SavatchaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sevimlilar': {
      id: '/sevimlilar'
      path: '/sevimlilar'
      fullPath: '/sevimlilar'
      preLoaderRoute: typeof SevimlilarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yetkazib-berish': {
      id: '/yetkazib-berish'
      path: '/yetkazib-berish'
      fullPath: '/yetkazib-berish'
      preLoaderRoute: typeof YetkazibBerishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mahsulot/$slug': {
      id: '/mahsulot/$slug'
      path: '/mahsulot/$slug'
      fullPath: '/mahsulot/$slug'
      preLoaderRoute: typeof MahsulotSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AloqaRoute: AloqaRoute,
  BizHaqimizdaRoute: BizHaqimizdaRoute,
  CheckoutRoute: CheckoutRoute,
  ChegirmalarRoute: ChegirmalarRoute,
  FaqRoute: FaqRoute,
  KategoriyalarRoute: KategoriyalarRoute,
  MahsulotlarRoute: MahsulotlarRoute,
  ProfilRoute: ProfilRoute,
  SavatchaRoute: SavatchaRoute,
  SevimlilarRoute: SevimlilarRoute,
  YetkazibBerishRoute: YetkazibBerishRoute,
  MahsulotSlugRoute: MahsulotSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
